version: '3'

services:
  mysql:
    image: mysql:5.7
    hostname: mysql_local
    container_name: mysql_local
    environment:
      - "MYSQL_ROOT_PASSWORD=test"
      - "TZ=Asia/Shanghai"
    volumes:
      - /var/container_data/db/mysql:/var/lib/mysql
      - /var/container_data/db/conf:/etc/mysql/conf.d
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - ms
  redis:
    image: redis:6.2.6
    container_name: redis
    hostname: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - /var/container_data/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - ms
  kafka:
    image: bitnami/kafka:3
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://114.115.244.230:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CREATE_TOPICS: "test-topic:1:1"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - ms

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    networks:
      - ms
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /var/container_data/es:/usr/share/elasticsearch/data
    networks:
      - ms
  jaeger:
    image: jaegertracing/all-in-one:1.27
    container_name: jaeger
    hostname: jaeger
    ports:
      - "16686:16686"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    depends_on:
      - es
    restart: always
    networks:
      - ms
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "6686:6686"
    volumes:
      - /var/container_data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/container_data/nginx/htpasswd:/etc/nginx/htpasswd:ro
    depends_on:
      - jaeger
    networks:
      - ms
networks:
  ms:
